dist: xenial
sudo: true
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python sql/pg.py e
- git diff
notifications:
  slack:
    secure: eJwjlY/1YrAH9CcyXmz6P5hSUTBrw4iUI7b7gb+5xnP4DPTs5Z9tQ0E/Yzio4ymZMu5UoglkxS2isDiImXHP7ZMm7HXGC/JbK88GADWMtNZCrDeaOwqAIpoZAP2LDHVG1mwYNrWRX/JRH+j3CT7EHPftPHOgNTx0XDoh51xJ8v3VuEFmgBJafZUp06FKzfWnLYT92wnbS02E/QbdGNp4Lf5DYDNNx8aBWhd1Iq7eGqeoKLJUWsgVa4F8BmNe80//dcE8FQ2mqj3rao/AO0cTsHLIjzNYSj3+ws6jbjDu4snltcXR0xKZLY+EHzKn6OQO0nNqYSCRuuEf/dVm4XSoKNDb5sou8zRdU+sPRLzwbWHThyUzCk+LD6KHfb97fu9Hvi0I4STE3Y+rM3JHViuL23P9EfMT62rXDoToS6/1q1lfIKYGodHjQb9csmD/Cq22/LaIdT8pogBn+hFsfqHoYbJHp42mSH861w9l0xUxwVhgrHVru5/fR+Fn80HqRfdb9i9ZzkD/KdavD2sncCeRii8RZ6uSqBYbrxjheU7h9ejrCAINu9OsxDhODsKzOakWW4uvIolliWt8YEEtnWmbAv/aBMveqtageU+iIa3htD5l4+V2lHjfpNnr2EUIUN5U95V43Ng7RDcBb5Ii6nLxqxX3zYLG9f5X/aeIY8AriLc=
